### ISSUE TITLE
Angular 18 support ?

### ISSUE THREAD

**Issue by umeli** [ashish-chopra/ngx-gauge#149]
Hi
We're currently stuck with using npm i --force, until this library releases with angular 18 support.
Thank you in advance

**Comment by ashish-chopra** [comment]
Hi there,

I'm gonna do that this week.

Thanks

**Comment by MarcelBariakGrenzebach** [comment]
Hi @ashish-chopra, any news about migration to angular 18?

**Comment by ashish-chopra** [comment]
Sorry, I didn't get the chance to do it. I will try publishing it this long weekend. 🤞

**Comment by DevAliMaher** [comment]
@ashish-chopra any updates ?!

**Comment by HolzmannSpace** [comment]
any updates?

**Comment by ashish-chopra** [comment]
I have been working on it. It's thrown by some compilation issues with
Angular Material.

Trying to finish it by this weekend.

**Comment by ugolman88** [comment]
Hi ashish-chopra any news?

**Comment by devabdurasul** [comment]
Hi, any updates on this?

**Comment by 188599** [comment]
There's an open [PR](https://github.com/ashish-chopra/ngx-gauge/pull/153) for this. Would be nice to see it merged and have it officially supported.

**Comment by ashish-chopra** [comment]
Reviewing the PR, thanks for sharing. FYI, I did an upgrade in my local but couldn't publish it because when I am trying to include GaugeModule into a sample project in v18, the gauge component couldn't get imported. Somehow it is related to the standalone component concept appearing as impediment which I didn't get time to fix though. 

I'm reviewing this PR and see if it can solve the issue.

**Comment by PichurinR** [comment]
Hello, we are all eagerly awaiting the support of Angular 18 and have faith in the developer!

**Comment by ashish-chopra** [comment]
Finally, the ng is updated to v18. And sorry for the delay, I will be keeping up to date with updating angular version on time going further, unless i am dead.

**Comment by johanrg** [comment]
Thanks for merging the PR.
