### ISSUE TITLE
Is it possible to remove the thousands separator (comma)

### ISSUE THREAD

**Issue by dombre77** [ashish-chopra/ngx-gauge#48]
Hello,
I use high values like 12000 sheets/hour in that gauge,but in Germany we use no thousands seperator or maybe a point instead the comma. Is it possible to select a point for separating or even remove that char? Thank you.

Regards, Dominik

**Comment by fernandocode** [comment]
Hello,

If I understand your problem it is possible to work around using [Custom Directives for display text](https://github.com/ashish-chopra/ngx-gauge#custom-directives-for-display-text).

I created [this example to demonstrate](https://stackblitz.com/edit/angular-wec9de), if your problem is another, create an example to analyze better.

**Comment by dombre77** [comment]
Hello Fernando,
thank you for that solution, that was exactly what I needed.

Regards, Dominik
