### ISSUE TITLE
Feature Request: Reverse Scale

### ISSUE THREAD

**Issue by barretodaniel** [ashish-chopra/ngx-gauge#5]
I was wondering if you had any plans to allow for the scale of the gauge to be reversed. I have a use case where as the value decreases I'd like the gauge to filled.

**Comment by ashish-chopra** [comment]
Hi @barretodaniel 

I can't commit anything on bringing reverse scale feature, neither i tried it myself with Gauge. Actually currently i have many things on my plate to finish before i get on working on new feature.

But i will take care of it in future. But by any chance you will able to add that feature, don't forget to send the pull request!

Why don't you just mention one of the concrete use case here, so that i will keep into my mind while working?

Thanks
Ashish

**Comment by ashish-chopra** [comment]
Hi @barretodaniel 

I have tried reverse scale by swapping the values of min and max and gauge is working fine with reverse scale as well. In addition to it. Kindly check the feature and reopen the issue in case if you expected something different. 

THanks!
