### ISSUE TITLE
How to add icon in middle of guage if value is 100% complete

### ISSUE THREAD

**Issue by sateesh-hub** [ashish-chopra/ngx-gauge#64]

**Comment by ashish-chopra** [comment]
You can use `<ngx-gauge-label>` instead of "label" attribute to do custom display of icons in the label field and use any logic to display.

For example:

```
<ngx-gauge [value]="currentValue" label="speed" append="km/h">
    <ngx-gauge-label *ngIf="currentValue == 100">
        New label
    </ngx-gauge-label>
  </ngx-gauge>
```

The new label will be visible only when `currentValue` is `100`, otherwise, the default label is shown. In your case replace new label with the icon.
