### ISSUE TITLE
[Enhancement] Show value as string

### ISSUE THREAD

**Issue by SpartanNico94** [ashish-chopra/ngx-gauge#9]
I'm using gauges to show values about something like "usage", for example "10/15Gb used". It could be useful to set shown value as string so will be possible to show "16k/20k" because if values are very large you can see it followed by "..." and it isn't good i think. 
What do you think about this?

**Comment by SpartanNico94** [comment]
@fernandocode thanks for your work. Your code works very well!

**Comment by fernandocode** [comment]
I'm glad that worked for your case, too @SpartanNico94 .  

Just wait for the PR to be analyzed and accepted in the official project.

**Comment by SpartanNico94** [comment]
Sure, now i've tried it and i confirm that works as expected. When your code will be accepted by @ashish-chopra I'll update the original package. Thanks again

**Comment by ashish-chopra** [comment]
Thanks everyone for your contribution.

@fernandocode I checked the pull request you sent. It is perfect for the use case you implemented for. However, I am looking for the more general use case. Additionally, I do not want to lose the flavor of declarative programming of Angular.

I propose API as following:

```
<ngx-gauge [value]="myValueVar">
    <ngx-gauge-value-text>
        <!-- here you can put anything you want. 
               Works for almost all use cases.
      -->
   </ngx-gauge-value-text>
</ngx-gauge
```

In this API, `value` provides the numeric value for rendering the gauge. and `<ngx-gauge-value-text>` can take any HTML, or binded expression or icons, and pipes etc (sky is the limit).

Another choice of API would be:
```
<ngx-gauge [value]="myValueVar">
<span ngxGaugeValueText>{{ myValueVar | number}}</span>
</ngx-gauge>
```
Choosing between `<ngx-gauge-value-text>` or `[ngxGaugeValueText]`, which and why?

What do you think of this APIs? Do you think of any usecase which does not cater with it?

**Comment by SpartanNico94** [comment]
In my opinion, I would choose the first option because in this way you'll give to the developers the flexibility to render the gauge as he/she wants, instead using a <span> that inline the code. Am I right?
 
A very nice feature related to the gauge rendering, would be that the gauge should be drawn around the text in order to avoid the dots. I don't know if it is possible, but an elegant way to avoid dots when text is greater than X chars I think would be appreciated. Maybe using the first option with appropriate HTML code this usecase is covered.

Thanks for your support 🥇

**Comment by fernandocode** [comment]
@ashish-chopra, you're right, this would be a more efficient and elegant way of doing this kind of treatment, in angular mode.

I believe it would not cause any limitation, on the contrary it would make it even more flexible, like using pipes or even called training methods.

Another point that I think relevant to comment on this implementation is the possibility that append and prepend can also be customized in the same way. (I have in the same context use cases that I have to modify or remove the append based on the current value).
And maybe the label can receive the same possibility. What do you think of that?

Do you have any work going on about this? Because I can try to make these implementations in the next days and replace my previous PR.

**Comment by fernandocode** [comment]
@SpartanNico94, about the three points in long texts.

Everything is based on the size of the canvas from the size attribute (which by default is 200). So the text will have a limited size, so I believe that the three points is an elegant option, but in counterpoint if the implementation is carried out as suggested by @ashish-chopra  it will be possible to add elements and styles around the text, so you can do customized treatments, such as font size and use of the three points for long texts, so by analyzing a case use it is possible that this is solved with this implementation.

**Comment by SpartanNico94** [comment]
> Another point that I think relevant to comment on this implementation is the possibility that append and prepend can also be customized in the same way. (I have in the same context use cases that I have to modify or remove the append based on the current value).
And maybe the label can receive the same possibility. What do you think of that?

Actually append and prepend are strings, so you can handle them if needed. For example i have a list of gaugesProperty and I render gauges in a for loop. The only problem is with "value" property

**Comment by SpartanNico94** [comment]
> such as font size  

in fact i've extended your code adding a new attribute called "font_size" that renders text using the provided size and using 'px' as unit.

**Comment by ashish-chopra** [comment]
@fernandocode Yes, I have started on this. But if you can send a PR, that would be good. Make sure to remove examples from the intial repo, else I will not be able to take it. If you want to show an example, try stackblitz, that is what I am exploring these days! It's simple just transfer your code to it and it will do the rest.

Yes, I have thought of all of the following:
1. ngx-gauge-prepend
2. ngx-gauge-append
3. ngx-gauge-label
4. ngx-gauge-value

Following things to be kept in mind while designing it:
1. Backwards compatibility
2. We should not create HTML soup which looks tacky.
3. Need to take care of CSS. How much CSS to be provided by gauge and how much user can customize need to see all possible combinations.

If possible can you look around how to add responsiveness to gauge. As people has asked about it, we can incorporate that too in new release.

@SpartanNico94  Well this is not possible to draw gauge around the text. Because we give a defined size to gauge. If you have something going inside gauge's label and it is bleeding out, that means you either have added too much into the display or you have created a smaller gauge. Try to increase the size of the gauge, may be that helps in your case. But the new directives that we are trying to introduce to help with adding custom text in gauge's display. I will look into the CSS as well how much modification will be allowed.

But in case you want to change the display text size, try to figure out the class/style applied to value printed on gauge and change it by override CSS in your file. I have used `ViewEncapsulation.None` so your changes will override the gauge's styles hopefully. You may remove `text-overflow: ellipsis` as well.

**Comment by fernandocode** [comment]
#12 available @SpartanNico94

**Comment by SpartanNico94** [comment]
Thanks for your work @fernandocode @ashish-chopra. I really appreciate your support. I'll update this package asap.

**Comment by ashish-chopra** [comment]
I am reopening the issue to keep track of backlog items to be merged in master branch before next release.

**Comment by ashish-chopra** [comment]
Code merged in master branch and new library build published to npm. download the new version 
ngx-gauge@1.0.0-beta.4 for these features. 

Checkout README for more details on using custom directives for display text.
